# Generated by Django 5.2.8 on 2026-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_popular_unidades_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
    ]
