# Generated by Django 5.2.8 on 2026-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_add_parcelamento_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
    ]
