# Generated by Django 5.2.8 on 2026-02-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orcamento',
        ),
    ]
