# Generated by Django 5.2.8 on 2026-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_add_fase_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='fase_atual',
            field=models.CharField(blank=True, choices=[('ESTRUTURA', 'Estrutura'), ('PLACA', 'Placa'), ('ACABAMENTO', 'Acabamento')], max_length=15, null=True, verbose_name='Fase Atual (Mão de Obra)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.CharField(choices=[('PRODUTO', 'Produtos'), ('MAO_OBRA', 'Mão de Obra')], default='PRODUTO', max_length=10, verbose_name='Tipo de Orçamento'),
        ),
    ]
